### ISSUE TITLE
Add support for Rails i18n date/time formats

### ISSUE THREAD

**Issue by jeremyw** [jeremyw/stamp#6]
Add support for stamp examples in i18n formats:

``` yaml
en:
  date:
    formats:
      default: "1999-01-31"
      short: "Jan 1"
      long: "January 1, 1999"
```
